theme: jekyll-theme-cayman
title: Pascal's homepage
description: Documentation personnelle
timezone: Europe/Paris
lsi: false
safe: true
source: /
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
